### ISSUE TITLE
Any guide to build the x64 dll?

### ISSUE THREAD

**Issue by fuchanghao** [pinterf/TIVTC#2]
visual studio 2017 15.2(26430.12)
windows sdk 10.0.15063.0

win32 works fine but when building x64 it says.

> memset_simd.cpp(30): error C4235: 使用了非标准扩展: 不支持在此结构上使用“__asm”关键字

Also there's warning of using sprintf not sprintf_s

**Comment by pinterf** [comment]
Does it work when you specify 
#include "avs\config.h" 
at the top?

**Comment by fuchanghao** [comment]
added, the same error still appears.

in 

memset_simd.cpp
TdeintASM.cpp
THelper.cpp
TDeinterlanceYV12.cpp
TDeinterlanceYUY2.cpp

**Comment by pinterf** [comment]
Ahh, are you trying to build TIVTC or TDeint? Because only TIVTC is ported, TDeint is just put there as a separate project in the solution (and there is no release from that of course), because it has a lot of code duplication with TIVTC and I'm planning to put it together when I'll have some time. TDeint has already an old x64 build from the pre-avs+ era, so it was not necessary to port yet.

**Comment by fuchanghao** [comment]
Oh I see. So the TDeint part is still in dev right?

The TIVTC part works fine(without #include "avs\config.h").

There's only a small bug: PlanarFrame.cpp is ANSI not Unicode.

**Comment by pinterf** [comment]
Due to current msvc compiler internal error, I'll do a release later, though it happens only at TIVTC. I'm planning to recompile both into a usual Clang-msvc-xp set. The other reason for no release that TDeint changes were not tested too deeply.
