### ISSUE TITLE
1.0.11 crashes with QTGMC 3.360s

### ISSUE THREAD

**Issue by Selur** [pinterf/TIVTC#4]
1.0.11 crashes with QTGMC 3.360s, 1.0.10 works fine.
see: https://forum.doom9.org/showthread.php?p=1846572#post1846572 and following.

Would be nice if this could be fixed.

**Comment by Selur** [comment]
-> works when lates Avisynth+ (r2728) is used, but crashs with r2664

**Comment by mleise** [comment]
Since my doom9 account got created with 0 privileges, I'll ask here. How exactly was the problem fixed for you, because for me QTGMC 3.360s and later on very high settings make my script crash as well, but I don't use TIVTC. Everything else is the current version as of 2018-08-17. This is on amd64 in single-threaded mode. Symptoms were crashes without an error message using ffmpeg as host or black frames in MPC-HC.

**Comment by Selur** [comment]
I just updated Avisynth+ to the latest version,..

**Comment by mleise** [comment]
Thank you for your quick response. Since only AviSynth+ r2728 has the "scale_inputs" expr argument and older AviSynth+ versions would complain about that with a useful error message, we seem to have had different issues after all. The only changes in QTGMC 3.360 were optimizations in regards to new options for the math expression evaluator, adding clamping, "use_expr" or "scale_inputs". Possibly some of that JIT code needs to be ironed out still.

**Comment by pinterf** [comment]
Definitely need more info: the script itself, the log from Avsmeter -avsinfo, source format. But since it is not Tivtc related, maybe the Qtgmc doom9 forum is more appropriate place for the report and others could help as well.
