### ISSUE TITLE
tdeint full=false results in crash

### ISSUE THREAD

**Issue by Statick** [pinterf/TIVTC#7]
as it says
running tdeint with full=false setting results in a crash every time
works fine without this setting

using tivtc 1.0.14

**Comment by pinterf** [comment]
Hi, need more info, since full=false is OK for me for various other parameter combinations.
- (just to be sure, since this TDeint was a different project from TIVTC and was never released by me and still under work)
Have you built TDeint for yourselves so your report applies to my present github state?
- input video format
- processor type
- Avisynth version
- a possibly minimized script including all parameters, not only full=false.
Thanks

**Comment by Statick** [comment]
apologies, I thought TDeint was part of the TIVTC dll. I did not realise it was a separate project at all. so now I'm not even 100% certain what version of TDeint I'm running or where it's come from. this is likely to be the cause of the problem!

I'll try to figure out what's happening

**Comment by Statick** [comment]
right yeah there's a separate tdeint.dll and it's from 2010

I think I can understand why it's crashing lol

**Comment by pinterf** [comment]
The actual source here is quite stable though.

**Comment by Statick** [comment]
is there a released binary? I've no idea how to build it from the source

**Comment by pinterf** [comment]
Not yet

**Comment by Statick** [comment]
okay I'll keep an eye out for that in future then
cheers

**Comment by pinterf** [comment]
Check release page pls
